### ISSUE TITLE
Configure changefreq and priority

### ISSUE THREAD

**Issue by PikinerLiliya** [netlify-labs/netlify-plugin-sitemap#22] opened 2020-08-18 11:49 UTC
Hi!

Thanks for useful extension. 

Is there a way to change changefreq and priority values?

Thanks

**Comment by erezrokah** [comment] 2020-10-04 14:53
Closing as duplicate of https://github.com/netlify-labs/netlify-plugin-sitemap/issues/24 (this issue was opened first, but #24 is better described).

**Closed by erezrokah** 2020-10-04 14:53 UTC
Labels: duplicate, type: feature
